services:
    router:
        image: "jc21/nginx-proxy-manager:latest"
        container_name: router
        restart: always
        ports:
            - "80:80"
            - "81:81"
            - "443:443"
        volumes:
            - ~/infra/router/data:/data
            - ~/infra/router/letsencrypt:/etc/letsencrypt
        networks:
            - edge
            - routing
        tunnel:
            image: cloudflare/cloudflared:latest
            container_name: tunnel
            restart: always
            environment:
                - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
            extra_hosts:
                - "host.docker.internal:host-gateway"
            command: tunnel run
            networks:
                - edge
            volumes:
                - ~/infra/tunnel:/home/nonroot/.cloudflared
networks:
    edge:
        external: true
    routing:
        external: true
